### obtener todos los characters
GET http://localhost:3000/api/characters

### obtener un character
GET http://localhost:3000/api/characters/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### crear un nuevo character
POST http://localhost:3000/api/characters
Content-Type: application/json

{
  "name": "Gabinete",
  "descprod": "Contendrá todos los componentes funcionales de la misma"
}

### modificar un character (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/characters/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
  "name": "Memoria",
  "descprod": "Las memorias sirven para cargar y almacenar todas las instrucciones que se ejecutan en el procesador"  

}
### modificar un character (PATCH - recurso parcial)
PATCH http://localhost:3000/api/characters/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
  "descprod": "Una unidad central de procesamiento, o CPU, es una pieza de hardware que permite que tu computadora interactúe con todas las aplicaciones y programas instalados." 
}

### borrar un character
DELETE http://localhost:3000/api/characters/a02b91bc-3769-4221-beb1-d7a3aeba7dad